service: stripe-serverless

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  profile: serverless-demo


functions:
  stripePayment:
    handler: handler.stripePayment
    events:
        - http:
            path: stripePayment
            method: post
            cors: true
